name: Build Android APK

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip \
            libffi-dev libssl-dev libjpeg-dev zlib1g-dev \
            autoconf libtool pkg-config \
            libncurses5-dev libncursesw5-dev \
            ccache libltdl-dev
          pip install --upgrade pip wheel setuptools
          pip install buildozer cython==0.29.36

      - name: Build APK
        run: |
          buildozer android debug
        env:
          ANDROIDSDK: ${{ github.workspace }}/.buildozer/android/platform/android-sdk
          ANDROIDNDK: ${{ github.workspace }}/.buildozer/android/platform/android-ndk-r25b
        timeout-minutes: 120

      - uses: actions/upload-artifact@v4
        with:
          name: T0Trading-APK
          path: bin/*.apk
          if-no-files-found: warn
